# -*- coding: utf-8 -*-
"""Calculator Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3xEQyvpLd35ILPiEWRvwRUvWdQ1q_J2
"""

def operations_handler():
    while True:
        print("\n=== Operations Handler ===")
        print("Choose an operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '5':
            print("Exiting the operations handler. Goodbye!")
            break

        try:
            value1 = float(input("Enter the first value: "))
            value2 = float(input("Enter the second value: "))

            if choice == '1':
                outcome = value1 + value2
                print(f"The result of addition is: {outcome}")
            elif choice == '2':
                outcome = value1 - value2
                print(f"The result of subtraction is: {outcome}")
            elif choice == '3':
                outcome = value1 * value2
                print(f"The result of multiplication is: {outcome}")
            elif choice == '4':
                if value2 != 0:
                    outcome = value1 / value2
                    print(f"The result of division is: {outcome}")
                else:
                    print("Error: Division by zero is not allowed.")
            else:
                print("Invalid operation choice. Please select a valid option.")
        except ValueError:
            print("Invalid input. Please enter numeric values.")

operations_handler()