# -*- coding: utf-8 -*-
"""Password Generator Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3xEQyvpLd35ILPiEWRvwRUvWdQ1q_J2
"""

import random
import string

def create_key():
    print("Welcome to the Password Generator!")

    try:
        size = int(input("Enter the desired length of the password: "))
        if size <= 0:
            print("Please enter a positive number.")
            return
    except ValueError:
        print("Invalid input. Please enter a number.")
        return

    print("\nChoose the complexity level:")
    print("1. Numbers only")
    print("2. Letters only")
    print("3. Letters and numbers")
    print("4. Letters, numbers, and special characters")

    try:
        level = int(input("Enter your choice (1-4): "))
        if level not in [1, 2, 3, 4]:
            print("Invalid choice. Please enter a number between 1 and 4.")
            return
    except ValueError:
        print("Invalid input. Please enter a number.")
        return

    if level == 1:
        pool = string.digits
    elif level == 2:
        pool = string.ascii_letters
    elif level == 3:
        pool = string.ascii_letters + string.digits
    elif level == 4:
        pool = string.ascii_letters + string.digits + string.punctuation

    key = ''.join(random.choice(pool) for _ in range(size))

    print("\nGenerated Password:", key)

create_key()