# -*- coding: utf-8 -*-
"""To do list Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3xEQyvpLd35ILPiEWRvwRUvWdQ1q_J2
"""

class TaskManager:
    def __init__(self):
        self.entries = {}
        self.next_entry_id = 1

    def add_entry(self, entry):
        self.entries[self.next_entry_id] = entry
        print(f"Entry '{entry}' added successfully with ID: {self.next_entry_id}")
        self.next_entry_id += 1

    def update_entry(self, entry_id, new_entry):
        if entry_id in self.entries:
            old_entry = self.entries[entry_id]
            self.entries[entry_id] = new_entry
            print(f"Entry ID {entry_id} updated from '{old_entry}' to '{new_entry}'")
        else:
            print(f"Entry ID {entry_id} not found.")

    def delete_entry(self, entry_id):
        if entry_id in self.entries:
            removed_entry = self.entries.pop(entry_id)
            print(f"Entry ID {entry_id} ('{removed_entry}') deleted successfully.")
        else:
            print(f"Entry ID {entry_id} not found.")

    def list_entries(self):
        if not self.entries:
            print("No entries in the list.")
        else:
            print("Current Entries:")
            for entry_id, entry in self.entries.items():
                print(f"ID {entry_id}: {entry}")

task_manager = TaskManager()
task_manager.add_entry("Buy groceries")
task_manager.add_entry("Read a book")
task_manager.list_entries()
task_manager.update_entry(1, "Buy groceries and cook dinner")
task_manager.delete_entry(2)
task_manager.list_entries()